### ISSUE TITLE
no matches for kind "CronJob" in version "batch/v1beta1"

### ISSUE THREAD

**Issue by GoRoad** [lework/kainstall#42]
在k8s 1.25版本之后batch/v1beta1不再提供 CronJob API。
因此在安装cilium时会提示错误，在查看yaml文件后发现1.9.*版本的cilium后发现其中在脚本的3266行使用了过时的api
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-snapshot
  namespace: kube-system
```
